export const mockPatients = [
  {
    id: "PAT-001",
    name: "Ramesh Kumar",
    age: 45,
    symptoms: ["Fever", "Cough", "Body Pain"],
    vitals: { temp: "101.2°F", bp: "130/85", pulse: "88 bpm", spo2: "96%" },
    triage: "high" as const,
    timestamp: "2026-02-28 09:15",
    ashaWorker: "Sunita Devi",
    village: "Chandpur",
  },
  {
    id: "PAT-002",
    name: "Priya Sharma",
    age: 28,
    symptoms: ["Headache", "Nausea"],
    vitals: { temp: "99.1°F", bp: "120/80", pulse: "72 bpm", spo2: "98%" },
    triage: "monitor" as const,
    timestamp: "2026-02-28 09:42",
    ashaWorker: "Sunita Devi",
    village: "Chandpur",
  },
  {
    id: "PAT-003",
    name: "Suresh Yadav",
    age: 62,
    symptoms: ["Chest Pain", "Breathlessness"],
    vitals: { temp: "98.6°F", bp: "155/95", pulse: "102 bpm", spo2: "91%" },
    triage: "high" as const,
    timestamp: "2026-02-28 10:05",
    ashaWorker: "Meena Kumari",
    village: "Barhiya",
  },
  {
    id: "PAT-004",
    name: "Anita Devi",
    age: 35,
    symptoms: ["Zukam", "Sore Throat"],
    vitals: { temp: "99.8°F", bp: "118/76", pulse: "78 bpm", spo2: "97%" },
    triage: "safe" as const,
    timestamp: "2026-02-28 10:30",
    ashaWorker: "Geeta Rani",
    village: "Mohania",
  },
  {
    id: "PAT-005",
    name: "Mohan Lal",
    age: 55,
    symptoms: ["Fever", "Diarrhea", "Weakness"],
    vitals: { temp: "102.4°F", bp: "100/65", pulse: "96 bpm", spo2: "94%" },
    triage: "high" as const,
    timestamp: "2026-02-28 11:00",
    ashaWorker: "Meena Kumari",
    village: "Barhiya",
  },
  {
    id: "PAT-006",
    name: "Kavita Singh",
    age: 22,
    symptoms: ["Cough", "Mild Fever"],
    vitals: { temp: "100.0°F", bp: "115/75", pulse: "80 bpm", spo2: "97%" },
    triage: "monitor" as const,
    timestamp: "2026-02-28 11:22",
    ashaWorker: "Sunita Devi",
    village: "Chandpur",
  },
  {
    id: "PAT-007",
    name: "Raju Prasad",
    age: 40,
    symptoms: ["Skin Rash"],
    vitals: { temp: "98.4°F", bp: "122/78", pulse: "74 bpm", spo2: "98%" },
    triage: "safe" as const,
    timestamp: "2026-02-28 11:45",
    ashaWorker: "Geeta Rani",
    village: "Mohania",
  },
  {
    id: "PAT-008",
    name: "Lakshmi Bai",
    age: 70,
    symptoms: ["Fever", "Joint Pain", "Cough"],
    vitals: { temp: "101.8°F", bp: "145/90", pulse: "90 bpm", spo2: "93%" },
    triage: "high" as const,
    timestamp: "2026-02-28 12:10",
    ashaWorker: "Meena Kumari",
    village: "Barhiya",
  },
];

export const symptomChartData = [
  { symptom: "Fever", count: 18 },
  { symptom: "Cough", count: 14 },
  { symptom: "Zukam", count: 11 },
  { symptom: "Headache", count: 9 },
  { symptom: "Body Pain", count: 7 },
  { symptom: "Diarrhea", count: 5 },
];

export type Patient = (typeof mockPatients)[number];
export type TriageLevel = "high" | "monitor" | "safe";
